// lib/services/language_service.dart
import 'package:flutter/material.dart';

class LanguageService {
  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'language': 'Language',
      'save': 'Save',
      'welcome': 'Welcome',
      'Change Password': 'Change Password',
      'Current Password': 'Current Password',
      'New Password': 'New Password',
      'Confirm New Password': 'Confirm New Password',
      'MTG-text': 'Migrate to Google authentication for easier sign-in',
      'Disconnect Google': 'Disconnect Google',
      'Migrate to Google': 'Migrate to Google',
      'Settings': 'Settings',
      'Click the first point to close shape and save it':
          'Click the first point to close shape and save it',
      'Enter Environmental Parameters': 'Enter Environmental Parameters',
      'Predict': 'Predict',
      'Select Model': 'Select Model',
      'Select Crop': 'Select Crop',
      'Check Suitability': 'Check Suitability',
      'Sectors': 'Sectors',
      'Yields': 'Yields',
      'Edit Product': 'Edit Product',
      'Save Profile': 'Save Profile',
      'Edit Profile': 'Edit Profile',
      'Record Details': 'Record Details',
      'Product Information': 'Product Information',
      'Farmer Name': 'Farmer Name',
      'Farm Name': 'Farm Name',
      'Location': 'Location',
      'Farm Information': 'Farm Information',
      "Yield Information": "Yield Information",
      'Area harvested (Ha)': 'Area harvested (Ha)',
      'Yield Amount': 'Yield Amount',
      'Harvest Date': 'Harvest Date',
      'Value in (Php)': 'Value in (Php)',
      'Documentation': 'Documentation',
      'Additional Information': 'Additional Information',
      'Notes': 'Notes',
      'Delete Yield': 'Delete Yield',
      'Are you sure you want to delete this record?':
          'Are you sure you want to delete this record?',
      'Cancel': 'Cancel',
      'Delete': 'Delete',
      'Product Sector': 'Product Sector',
      'Product Name': 'Product Name',
      'Farms': 'Farms',
      'Add Record': 'Add Record',
      'Adding...': 'Adding...',
      'Farm Profile': 'Farm Profile',
      'Recent Records': ' Recent Records',
      'Products & Distribution': 'Products & Distribution',
      'Create Farm': 'Create Farm',
      'Create New Farm': 'Create New Farm',
      'Name is required': 'Name is required',
      'Tap to view details': 'Tap to view details',
      'Save Changes': 'Save Changes',
      'Barangay Details': 'Barangay Details',
      'Farms List': 'Farms List',
      'Yield Data': ' Yield Data',
      'Farm Owner': 'Farm Owner',
      'Associations': 'Associations',
      'Total Farms': 'Total Farms',
      'Total Farmers': ' Total Farmers',
      'Avg Farm Size': 'Avg Farm Size',
      'Annual Yield': 'Annual Yield',
      'Area Harvested': 'Area Harvested',
      'Annual Production': ' Annual Production',
      'Total Users': 'Total Users',
      'New Users': 'New Users',
      'Roles': 'Roles',
      'Inactive': 'Inactive',
      'Total Members': 'Total Members',
      'Active': 'Active',
      'Active Associations': 'Active Associations',
      'Total Associations': 'Total Associations',
      'Farmers': 'Farmers',
      'Total Production': 'Total Production',
      'Total Area': 'Total Area',
      'Unique Owners': 'Unique Owners',
      'Avg. Yield': 'Avg. Yield',
      'Growth %': 'Growth %',
      'Annual Growth': 'Annual Growth',
      'Reports': 'Reports',
      'No Report Generated': 'No Report Generated',
      'Configure your filters above and click "Generate Report" to create your first report.':
          'Configure your filters above and click "Generate Report" to create your first report.',
      'Get Started': 'Get Started',
      'No Data Found': 'No Data Found',
      'No Record':
          'No records match your current filter criteria. Try adjusting your filters or selecting a different date range.',
      'Reset Filters': 'Reset Filters',
      'Try Again': 'Try Again',
      'Generating report...': 'Generating report...',
      'Search...': 'Search...',
      'Report Filters': 'Report Filters',
      'Report Type': 'Report Type',
      'Generate Report': 'Generate Report',
      'Select Columns': 'Select Columns',
      'Crop Suitability': 'Crop Suitability',
      'Crop Recommendation': 'Crop Recommendation',
      'View Requirements': 'View Requirements',
      'RECOMMENDED': 'RECOMMENDED',
      'Alternative Options': 'Alternative Options',
      'View Details': 'View Details',
      'Model Consensus': 'Model Consensus',
      'Analysis Summary': 'Analysis Summary',
      'Crops Analyzed': 'Crops Analyzed',
      'Confidence Threshold': 'Confidence Threshold',
      'Low Confidence': 'Low Confidence',
      'Crop Requirements': 'Crop Requirements',
      'SUITABLE': 'SUITABLE',
      'NOT_SUITABLE': 'NOT_SUITABLE',
      'Confidence Level': 'Confidence Level',
      'AI Models Used': 'AI Models Used',
      'Parameter Analysis': 'Parameter Analysis',
      'parameters optimal': 'parameters optimal',
      'Current: ': 'Current: ',
      'Improvement Suggestions': ' Improvement Suggestions',
      'parameters need attention': 'parameters need attention',
      'disclaimer_ai':
          'AI suggestions should be verified with local agricultural experts',
      'Needs Attention': 'Needs Attention',
      'Get AI Suggestions': 'Get AI Suggestions',
      'Check Another Configuration': 'Check Another Configuration',
      'Select All': 'Select All',
      'Clear All': 'Clear All',
      'Apply Filters': 'Apply Filters',
      'No data available': 'No data available',
      'Land Area': 'Land Area',
      'Size:': 'Size:',
      'Plots:': 'Plots:',
      'Total Products': 'Total Products',
      'Varieties:': 'Varieties:' ,
      'Agriculture Assistant': 'Agriculture Assistant' ,
      'How can I help you today?': 'How can I help you today?',




      // Quick Topics Section
  'Quick Topics': 'Quick Topics',
  'Hide Quick Topics': 'Hide Quick Topics',
  'Show Quick Topics': 'Show Quick Topics',
  
  // Quick Option Cards
  'Soil Health': 'Soil Health',
  'Tell me about soil health and pH levels': 'Tell me about soil health and pH levels',
  
  'Crop Selection': 'Crop Selection',
  'What crops should I grow in my region?': 'What crops should I grow in my region?',
  
  'Pest Control': 'Pest Control',
  'How do I control pests organically?': 'How do I control pests organically?',
  
  'Irrigation': 'Irrigation',
  'What are the best irrigation practices?': 'What are the best irrigation practices?',
  
  'Fertilizers': 'Fertilizers',
  'Which fertilizers should I use for my crops?': 'Which fertilizers should I use for my crops?',
  
  'Planting Season': 'Planting Season',
  'When is the best time to plant crops?': 'When is the best time to plant crops?',
  
  'Plant Disease': 'Plant Disease',
  'How do I identify and treat plant diseases?': 'How do I identify and treat plant diseases?',
  
  'Weather Impact': 'Weather Impact',
  'How does weather affect crop growth?': 'How does weather affect crop growth?',
  
  // Input Field
  'Type here...': 'Type here...',
   




 'howOurAiModelsWork': 'How Our AI Models Work',
  'understandingCropRecommendations': 'Understanding crop recommendations',
  'previous': 'Previous',
  'next': 'Next',
  'close': 'Close',
  'howItWorks': 'How it works',
  'simpleAnalogy': 'Simple analogy',
  'bestFor': 'Best for',
  'Dismiss': 'Dismiss',
  
  'decisionTree': 'Decision Tree',
  'decisionTreeDescription': 'Like choosing crops step by step',
  'decisionTreeExplanation': 'Imagine deciding what to plant by asking simple questions one after another:\n\n• Is the soil nitrogen high? → Yes/No\n• Is rainfall above 500mm? → Yes/No\n• Is temperature warm? → Yes/No\n\nEach answer leads to the next question until we find the best crop.',
  'decisionTreeAnalogy': 'Like following a recipe: check ingredients, then steps, until dish is ready.',
  'decisionTreeBestFor': 'Easy to understand decisions',
  
  'randomForest': 'Random Forest',
  'randomForestDescription': 'Many experts voting together',
  'randomForestExplanation': 'This is like asking many experienced farmers for their opinion, then choosing the crop most farmers recommend.\n\nEach "farmer" (decision tree) looks at your land differently and votes for the best crop.',
  'randomForestAnalogy': 'Like a farmers\' committee - more reliable than one person\'s opinion.',
  'randomForestBestFor': 'Most accurate recommendations',
  
  'logisticRegression': 'Logistic Regression',
  'logisticRegressionDescription': 'Weighing what matters most',
  'logisticRegressionExplanation': 'This method learns which factors are most important for each crop:\n\n• Soil pH might be very important for tomatoes\n• Rainfall might be crucial for rice\n• Temperature might matter most for wheat\n\nIt then calculates the best match for your conditions.',
  'logisticRegressionAnalogy': 'Like giving scores to different factors and picking the highest score.',
  'logisticRegressionBestFor': 'Understanding which factors matter most',
  
  'xgBoost': 'XGBoost',
  'xgBoostDescription': 'Smart learning from mistakes',
  'xgBoostExplanation': 'This is our most advanced method that learns from its own mistakes.\n\nIt starts with basic recommendations, then improves by focusing on cases it got wrong previously, getting smarter with each round.',
  'xgBoostAnalogy': 'Like a student who reviews wrong answers to improve in next test.',
  'xgBoostBestFor': 'Highest accuracy with complex patterns',
   'Personal Information': 'Personal Information',
   'Full Name': 'Full Name',
   'Contact Number':' Contact Number',
   'Email':'Email',
   'Report a Technical Issue': 'Report a Technical Issue',
   'Having trouble with the platform? Let us know and we will help you resolve it.':'Having trouble with the platform? Let us know and we will help you resolve it.',
  'Describe the Issue *': 'Describe the Issue *',
  'contactus_hint_problem_description':' Please provide details such as:\n• What were you trying to do?\n• What happened instead?\n• Any error messages you saw\n• When did this problem start?',
  'Submit Issue Report': 'Submit Issue Report',
  "Our technical support team will review your issue and respond as soon as possible. For urgent system-wide issues, please call our hotline.":' Our technical support team will review your issue and respond as soon as possible. For urgent system-wide issues, please call our hotline.',
  'Need Urgent Help?': 'Need Urgent Help?',
  'Helpful Tips': 'Helpful Tips',
  'Include screenshots if possible': 'Include screenshots if possible',
  "Describe the exact steps you took": "Describe the exact steps you took",
  'Mention your device and browser': 'Mention your device and browser',
  'Note the time when issue occurred': 'Note the time when issue occurred',
  'Please describe the issue you\'re experiencing': 'Please describe the issue you\'re experiencing',
  'Please provide more details (at least 10 characters)':' Please provide more details (at least 10 characters)',
  'No notifications found':'No notifications found',
  'No notifications':'No notifications',
  'Try different search terms':'Try different search terms',
  'You dont have any notifications yet':'You dont have any notifications yet',
  'Clear Search':'Clear Search',


    },
    'fil': {

'Clear Search': 'I-clear ang Paghahanap',
'You dont have any notifications yet':'Wala ka pang mga notification',
'Try different search terms':'Subukan ang ibat ibang mga termino sa paghahanap',
'No notifications':'Walang mga notification',
'No notifications found':'Walang nahanap na mga notification',
'How can I help you today?':' Paano kita matutulungan ?',
'Please provide more details (at least 10 characters)': ' Mangyaring magbigay ng higit pang mga detalye (hindi bababa sa 10 mga character)',
'Please describe the issue you\'re experiencing': 'Mangyaring ilarawan ang isyu na iyong nararanasan',
'Note the time when issue occurred': 'Tandaan ang oras kung kailan nangyari ang isyu',
'Mention your device and browser':'Banggitin ang iyong device at browser',
"Describe the exact steps you took":'Ilarawan ang eksaktong mga hakbang na iyong ginawa',
'Include screenshots if possible':'Isama ang mga screenshot kung maaari',
'Helpful Tips':'Mga Kapaki-pakinabang na Tip',
 'Need Urgent Help?':'Kailangan ng Agarang Tulong?',
 'Our technical support team will review your issue and respond as soon as possible. For urgent system-wide issues, please call our hotline.':'Susuriin ng aming technical support team ang iyong isyu at tutugon sa lalong madaling panahon. Para sa mga agarang isyu sa buong sistema, mangyaring tawagan ang aming hotline.',
'Submit Issue Report': 'Isumite ang Ulat ng Isyu',
'contactus_hint_problem_description':' Mangyaring magbigay ng mga detalye tulad ng:\n• Ano ang sinusubukan mong gawin?\n• Ano ang nangyari sa halip?\n• Anumang mga mensahe ng error na nakita mo\n• Kailan nagsimula ang problemang ito?',
'Describe the Issue *': 'Ilarawan ang Isyu *',
'Having trouble with the platform? Let us know and we will help you resolve it.':'Nagkakaroon ng problema sa platform? Ipaalam sa amin at tutulungan ka naming malutas ito.',
  'Report a Technical Issue': 'Iulat ang Isang Teknikal na Isyu',
      'Email': 'Email',
      'Contact Number': 'Numero ng Pakikipag-ugnayan',
      'Full Name': 'Buong Pangalan',
'Personal Information': 'Personal na Impormasyon',
'howOurAiModelsWork': 'Paano Gumagana ang Aming AI Models',
  'understandingCropRecommendations': 'Pag-unawa sa mga rekomendasyon ng pananim',
  'previous': 'Nakaraan',
  'next': 'Susunod',
  'close': 'Isara',
  'howItWorks': 'Paano ito gumagana',
  'simpleAnalogy': 'Simpleng paghahalintulad',
  'bestFor': 'Pinakamainam para sa',
  'Dismiss': 'Balewalain',
  
  'decisionTree': 'Decision Tree',
  'decisionTreeDescription': 'Para sa pagpili ng pananim nang sunud-sunod',
  'decisionTreeExplanation': 'Isipin na nagdedesisyon kung ano ang itatanim sa pamamagitan ng pagtatanong ng mga simpleng katanungan:\n\n• Mataas ba ang nitrogen sa lupa? → Oo/Hindi\n• Ang ulan ba ay higit sa 500mm? → Oo/Hindi\n• Mainit ba ang temperatura? → Oo/Hindi\n\nBawat sagot ay nagdudulot sa susunod na katanungan hanggang mahanap natin ang pinakamahusay na pananim.',
  'decisionTreeAnalogy': 'Para sa pagsunod sa isang recipe: suriin ang mga sangkap, pagkatapos ay mga hakbang, hanggang handa na ang ulam.',
  'decisionTreeBestFor': 'Madaling maunawaang mga desisyon',
  
  'randomForest': 'Random Forest',
  'randomForestDescription': 'Maraming eksperto ang bumoboto nang magkasama',
  'randomForestExplanation': 'Ito ay tulad ng pagtatanong sa maraming may karanasang magsasaka para sa kanilang opinyon, pagkatapos ay pipiliin ang pananim na inirerekomenda ng karamihan.\n\nBawat "magsasaka" (decision tree) ay tumitingin sa iyong lupain nang iba at bumoboto para sa pinakamahusay na pananim.',
  'randomForestAnalogy': 'Tulad ng isang komite ng mga magsasaka - mas maaasahan kaysa sa opinyon ng isang tao.',
  'randomForestBestFor': 'Pinakatumpak na mga rekomendasyon',
  
  'logisticRegression': 'Logistic Regression',
  'logisticRegressionDescription': 'Tinitimbang kung ano ang pinakamahalaga',
  'logisticRegressionExplanation': 'Ang pamamaraang ito ay natututo kung aling mga kadahilanan ang pinakamahalaga para sa bawat pananim:\n\n• Ang pH ng lupa ay maaaring napakahalaga para sa mga kamatis\n• Ang pag-ulan ay maaaring mahalaga para sa palay\n• Ang temperatura ay maaaring pinakamahalaga para sa trigo\n\nPagkatapos ay kinakalkula nito ang pinakamahusay na pagtutugma para sa iyong mga kondisyon.',
  'logisticRegressionAnalogy': 'Tulad ng pagbibigay ng mga puntos sa iba\'t ibang mga kadahilanan at pagpili ng pinakamataas na iskor.',
  'logisticRegressionBestFor': 'Pag-unawa kung aling mga kadahilanan ang mahalaga',
  
  'xgBoost': 'XGBoost',
  'xgBoostDescription': 'Matalinong pag-aaral mula sa mga pagkakamali',
  'xgBoostExplanation': 'Ito ang aming pinaka-advanced na pamamaraan na natututo mula sa sarili nitong mga pagkakamali.\n\nNagsisimula ito sa mga pangunahing rekomendasyon, pagkatapos ay pinabuting sa pamamagitan ng pagtuon sa mga kaso na mali ito dati, at nagiging mas matalino sa bawat ikot.',
  'xgBoostAnalogy': 'Tulad ng isang mag-aaral na nagsusuri ng mga maling sagot upang mapabuti sa susunod na pagsusulit.',
  'xgBoostBestFor': 'Pinakamataas na katumpakan sa mga kumplikadong pattern',

 // Quick Topics Section
  'Quick Topics': 'Mabilis na Paksa',
  'Hide Quick Topics': 'Itago ang Mabilis na Paksa',
  'Show Quick Topics': 'Ipakita ang Mabilis na Paksa',
  
  // Quick Option Cards 
  'Soil Health': 'Kalusugan ng Lupa',
  'Tell me about soil health and pH levels': 'Sabihin mo sa akin ang tungkol sa kalusugan ng lupa at pH levels',
  
  'Crop Selection': 'Pagpili ng Pananim',
  'What crops should I grow in my region?': 'Anong pananim ang dapat kong itanim sa aking rehiyon?',
  
  'Pest Control': 'Kontrol ng Peste',
  'How do I control pests organically?': 'Paano ko kontrolin ang peste nang organiko?',
  
  'Irrigation': 'Irigasyon',
  'What are the best irrigation practices?': 'Ano ang pinakamahusay na mga gawain sa irigasyon?',
  
  'Fertilizers': 'Pataba',
  'Which fertilizers should I use for my crops?': 'Aling pataba ang dapat kong gamitin para sa aking pananim?',
  
  'Planting Season': 'Panahon ng Pagtatanim',
  'When is the best time to plant crops?': 'Kailan ang pinakamahusay na panahon upang magtanim ng pananim?',
  
  'Plant Disease': 'Sakit ng Halaman',
  'How do I identify and treat plant diseases?': 'Paano ko makikilala at gagamutin ang mga sakit ng halaman?',
  
  'Weather Impact': 'Epekto ng Panahon',
  'How does weather affect crop growth?': 'Paano nakakaapekto ang panahon sa paglaki ng pananim?',
  
  // Input Field
  'Type here...': 'Mag-type dito...',
      'Agriculture Assistant': ' Katulong sa Agrikultura', 
      'Varieties:': 'Iba t Ibang Uri:',
      'Total Products': 'Kabuuang Mga Produkto',
      'Plots:': 'Mga Plots:',
      'Size:': 'Laki:',
      'Land Area': 'Lupang Sakahan',
      'No data available': 'Walang available na data',
      'Apply Filters': 'I-apply ang Mga Filter',
      'Clear All': 'I-clear Lahat',
      'Select All': 'Piliin Lahat',
      'Check Another Configuration': 'Suriin ang Ibang Konfigurasyon',
      'Get AI Suggestions': 'Kumuha ng Mga Mungkahi ng AI',
      'Needs Attention': 'Nangangailangan ng Pansin',
      'disclaimer_ai':
          'Ang mga mungkahi ng AI ay dapat beripikahin sa mga lokal na eksperto sa agrikultura',
      'parameters need attention': 'mga parameter na nangangailangan ng pansin',
      'Improvement Suggestions': ' Mga Mungkahi sa Pagpapabuti',
      'Current: ': 'Kasalukuyan: ',
      'parameters optimal': 'mga parameter na optimal',
      'Parameter Analysis': 'Pagsusuri ng Parameter',
      'AI Models Used': 'Mga Ginamit na Modelo ng AI',
      'Confidence Level': 'Antas ng Kumpiyansa',
      'NOT_SUITABLE': 'HINDI ANGKOP',
      'SUITABLE': 'ANGKOP',
      'Crop Requirements': 'Mga Kinakailangan sa Pananim',
      'Low Confidence': 'Mababang Kumpiyansa',
      'Confidence Threshold': 'Confidence Threshold',
      'Crops Analyzed': 'Mga Pananim na Nasuri',
      'Analysis Summary': 'Buod ng Pagsusuri',
      'Model Consensus': 'Konsensus ng Modelo',
      'View Details': 'Tingnan ang Mga Detalye',
      'Alternative Options': 'Mga Alternatibong Opsyon',
      'RECOMMENDED': 'INIREREKOMENDA',
      'View Requirements': 'Tingnan ang Mga Kinakailangan',
      'Crop Recommendation': 'Rekomendasyon na Pananim',
      'Crop Suitability': 'Angkop ng Pananim',
      'Select Columns': 'Pumili ng Mga Column',
      'Generate Report': 'Gumawa ng Ulat',
      'Report Type': 'Uri ng Ulat',
      'Report Filters': 'Mga Filter ng Ulat',
      'Search...': 'Maghanap...',
      'Generating report...': 'Gumagawa ng ulat...',
      'Try Again': 'Subukang Muli',
      'Reset Filters': 'I-reset ang mga Filter',
      'No Record':
          'Walang rekord na tumutugma sa iyong kasalukuyang mga pamantayan sa filter. Subukang ayusin ang iyong mga filter o pumili ng ibang saklaw ng petsa.',
      'No Data Found': 'Walang Nahanap na Data',
      'Get Started': 'Magsimula',
      'Configure your filters above and click "Generate Report" to create your first report.':
          'I-configure ang iyong mga filter sa itaas at i-click ang "Generate Report" upang lumikha ng iyong unang ulat.',
      'No Report Generated': 'Walang Nabuong Ulat',
      'Reports': 'Ulat',
      'Annual Growth': 'Taunang Paglago',
      'Growth %': 'Paglago %',
      'Avg. Yield': 'Karaniwang Ani',
      'Unique Owners': 'Natatanging mga May-ari',
      'Total Area': 'Kabuuang Lupa',
      'Total Production': 'Kabuuang Produksyon',
      'Farmers': 'Mga Magsasaka',
      'Total Associations': 'Kabuuang mga Asosasyon',
      'Active Associations': 'Aktibong Mga Asosasyon',
      'Active': 'Aktibo',
      'Total Members': 'Kabuuang mga Miyembro',
      'Inactive': 'Hindi Aktibo',
      'Roles': 'Mga Role',
      'New Users': 'Mga Bagong User',
      'Total Users': 'Kabuuang mga User',
      'Annual Production': 'Taunang Produksyon',
      'Area Harvested': 'Lupang Inani',
      'Annual Yield': 'Taunang Ani',
      'Avg Farm Size': 'Karaniwang Laki ng Sakahan',
      'Total Farms': 'Kabuuang mga Sakahan',
      'Total Farmers': 'Kabuuang mga Magsasaka',
      'Associations': ' Mga Asosasyon',
      'Farm Owner': ' May-ari ng Sakahan',
      'Yield Data': ' Datos ng Ani',
      'Farms List': 'Listahan ng mga Sakahan',
      'Barangay Details': 'Mga Detalye ng Barangay',
      'Save Changes': 'I-save ang mga Pagbabago',
      'Tap to view details': 'I-tap upang makita ang mga detalye',
      'Name is required': 'Kinakailangan ang Pangalan',
      'Create New Farm': 'Gumawa ng Bagong Sakahan',
      'Create Farm': 'Gumawa ng Sakahan',
      'products & Distribution': 'Mga Produkto at Distribusyon',
      'Recent Records': 'Mga Kamakailang Rekord',
      'Farm Profile': 'Profile ng Sakahan',
      'Adding...': 'Dinadagdag...',
      'Add Record': 'Magdagdag ng Rekord',
      'Farms': 'Mga Sakahan',
      'Product Name': 'Pangalan ng Produkto',
      'Product Sector': 'Sektor ng Produkto',
      'Delete': 'Burahin',
      'Cancel': 'Kanselahin',
      'Are you sure you want to delete this record?':
          'Sigurado ka bang gusto mong tanggalin ang rekord na ito?',
      'Delete Yield': 'Tanggalin ang Ani',
      'Notes': 'Mga Tala',
      'Additional Information': 'Karagdagang Impormasyon',
      'Documentation': 'Dokumentasyon',
      'Value in (Php)': 'Halaga sa (Php)',
      'Harvest Date': 'Petsa ng Pag-aani',
      'Yield Amount': 'Dami ng Ani',
      'Yield Information': 'Impormasyon sa Ani',
      'Area harvested (Ha)': 'Lupang inani (Ha)',
      'Farm Name': 'Pangalan ng Sakahan',
      'Farm Information': 'Impormasyon sa Sakahan',
      "Location": "Lokasyon",
      "Farmer Name": "Pangalan ng Magsasaka",
      "Product Information": "Impormasyon ng Produkto",
      'Record Details': 'Mga Detalye ng Rekord',
      'Edit Product': 'I-edit ang Produkto',
      'Edit Profile': 'I-edit ang Profile',
      'Save Profile': 'I-save ang Profile',
      'Yields': 'Ani',
      'Sectors': 'Mga Sektor',
      'language': 'Wika',
      'save': 'I-save',
      'welcome': 'Maligayang pagdating',
      'Change Password': 'Palitan ang Password',
      'Current Password': 'Kasalukuyang Password',
      'New Password': 'Bagong Password',
      'Confirm New Password': 'Kumpirmahin ang Bagong Password',
      'MTG-text':
          'Mag-migrate sa Google authentication para sa mas madaling pag-sign-in',
      'Disconnect Google': 'I-disconnect ang Google',
      'Migrate to Google': 'I-migrate sa Google',
      'Settings': 'Mga Setting',
      ''
              'Click the first point to close shape and save it':
          'I-click ang unang punto upang isara ang hugis at i-save ito',
      'Enter Environmental Parameters':
          'Ilagay ang mga Parameter ng Kapaligiran',
      'Predict': 'Hulaan',
      'Select Model': 'Pumili ng Modelo',
      'Select Crop': 'Pumili ng Pananim',
      'Check Suitability': 'Suriin ang Angkop',
    },
  };

  static String t(String key, {String languageCode = 'en'}) {
    return _translations[languageCode]?[key] ??
        _translations['en']![key] ??
        key;
  }

  static const supportedLocales = [
    Locale('en'),
    Locale('fil'),
  ];
}
