// farmer_data.dart

class FarmerData {
  static List<String> barangays = [
    "San Diego",
    "Santo Angel",
    "San Roque",
    "San Crispin",
    "San Juan",
    "San Marcos",
    "Santa Maria Magdalena",
    "Del Remedio",
    "San Rafael",
    "Santa Monica",
    "San Isidro",
    "Santa Veronica",
    "Santisimo Rosario",
    "San Bartolome",
    "Bautista",
    "San Isidro",
    "Santisimo Rosario",
    "San Antonio 2",
    "San Cristobal",
    "Santa Cruz",
    "San Antonio 1",
    "San Gregorio",
    "Soledad",
    "Santa Maria",
    "San Joaquin",
    "San Gregorio",
    "San Ignacio",
    "Santo Niño",
    "San Vicente",
    "Concepcion",
    "Santa Isabel",
    "San Jose",
    "San Pedro",
    "San Mateo",
    "Santa Ana",
    "Dolores",
    "San Buenaventura",
    "San Lorenzo",
    "Santa Catalina",
    "Santa Elena",
    "Santo Cristo",
    "San Francisco",
    "San Gabriel",
    "San Miguel",
    "IV-A",
    "IV-B",
    "IV-C",
    "Santiago 2",
    "Santiago 1",
    "II-B",
    "II-C",
    "II-D",
    "II-E",
    "II-F",
    "III-A",
    "III-B",
    "III-C",
    "III-D",
    "III-E",
    "III-F",
    "VI-A",
    "VI-B",
    "VI-D",
    "VI-E",
    "V-A",
    "V-B",
    "V-C",
    "V-D",
    "VII-A",
    "VII-B",
    "VII-C",
    "VII-D",
    "VII-E",
    "I-A",
    "I-B",
    "San Lucas 1",
    "San Lucas 2",
    "Bagong Pook",
    "II-A",
    "Santa Filomena",
    "Bagong Bayan",
    "Atisan"
  ];

  static List<Map<String, dynamic>> farmers = [
    // Rice Farmers (5)
    {
      'id': '1',
      'farmerName': 'Juan Dela Cruz',
      'sector': 'Rice',
      'barangay': 'San Juan',
      'contact': '09123456789',
      'imageUrl':
          'https://res.cloudinary.com/dk41ykxsq/image/upload/v1745590990/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTAxL3JtNjA5LXNvbGlkaWNvbi13LTAwMi1wLnBuZw-removebg-preview_myrmrf.png',
      'farmName': 'Golden Grains Rice Farm',
      'hectare': 5.2,
    },
    {
      'id': '2',
      'farmerName': 'Ricardo Mendoza',
      'sector': 'Rice',
      'barangay': 'San Isidro',
      'contact': '09234567891',
      'imageUrl':
          'https://res.cloudinary.com/dk41ykxsq/image/upload/v1745590990/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTAxL3JtNjA5LXNvbGlkaWNvbi13LTAwMi1wLnBuZw-removebg-preview_myrmrf.png',
      'farmName': 'Mendoza Rice Fields',
      'hectare': 3.8,
    },
    {
      'id': '3',
      'farmerName': 'Eduardo Santos',
      'sector': 'Rice',
      'barangay': 'Santa Maria Magdalena',
      'contact': '09345678912',
      'imageUrl':
          'https://res.cloudinary.com/dk41ykxsq/image/upload/v1745590990/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTAxL3JtNjA5LXNvbGlkaWNvbi13LTAwMi1wLnBuZw-removebg-preview_myrmrf.png',
      'farmName': 'Santos Rice Plantation',
      'hectare': 7.5,
    },
    {
      'id': '4',
      'farmerName': 'Alfredo Reyes',
      'sector': 'Rice',
      'barangay': 'San Rafael',
      'contact': '09456789123',
      'imageUrl':
          'https://res.cloudinary.com/dk41ykxsq/image/upload/v1745590990/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTAxL3JtNjA5LXNvbGlkaWNvbi13LTAwMi1wLnBuZw-removebg-preview_myrmrf.png',
      'farmName': 'Reyes Family Rice Farm',
      'hectare': 4.0,
    },
    {
      'id': '5',
      'farmerName': 'Carlos Lopez',
      'sector': 'Rice',
      'barangay': 'San Diego',
      'contact': '09567891234',
      'imageUrl':
          'https://res.cloudinary.com/dk41ykxsq/image/upload/v1745590990/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTAxL3JtNjA5LXNvbGlkaWNvbi13LTAwMi1wLnBuZw-removebg-preview_myrmrf.png',
      'farmName': 'Lopez Rice Estate',
      'hectare': 6.3,
    },

    // Corn Farmers (5)
    {
      'id': '6',
      'farmerName': 'Maria Santos',
      'sector': 'Corn',
      'barangay': 'San Roque',
      'contact': '09234567890',
      'imageUrl':
          'https://res.cloudinary.com/dk41ykxsq/image/upload/v1745590990/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTAxL3JtNjA5LXNvbGlkaWNvbi13LTAwMi1wLnBuZw-removebg-preview_myrmrf.png',
      'farmName': 'Santos Corn Fields',
      'hectare': 4.5,
    },
    {
      'id': '7',
      'farmerName': 'Roberto Garcia',
      'sector': 'Corn',
      'barangay': 'San Crispin',
      'contact': '09345678901',
      'imageUrl':
          'https://res.cloudinary.com/dk41ykxsq/image/upload/v1745590990/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTAxL3JtNjA5LXNvbGlkaWNvbi13LTAwMi1wLnBuZw-removebg-preview_myrmrf.png',
      'farmName': 'Garcia Corn Farm',
      'hectare': 3.2,
    },
    {
      'id': '8',
      'farmerName': 'Antonio Torres',
      'sector': 'Corn',
      'barangay': 'Santa Veronica',
      'contact': '09456789012',
      'imageUrl':
          'https://res.cloudinary.com/dk41ykxsq/image/upload/v1745590990/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTAxL3JtNjA5LXNvbGlkaWNvbi13LTAwMi1wLnBuZw-removebg-preview_myrmrf.png',
      'farmName': 'Torres Corn Plantation',
      'hectare': 5.7,
    },
    {
      'id': '9',
      'farmerName': 'Lourdes Hernandez',
      'sector': 'Corn',
      'barangay': 'San Bartolome',
      'contact': '09567890123',
      'imageUrl':
          'https://res.cloudinary.com/dk41ykxsq/image/upload/v1745590990/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTAxL3JtNjA5LXNvbGlkaWNvbi13LTAwMi1wLnBuZw-removebg-preview_myrmrf.png',
      'farmName': 'Hernandez Corn Fields',
      'hectare': 4.8,
    },
    {
      'id': '10',
      'farmerName': 'Fernando Castro',
      'sector': 'Corn',
      'barangay': 'San Marcos',
      'contact': '09678901234',
      'imageUrl':
          'https://res.cloudinary.com/dk41ykxsq/image/upload/v1745590990/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTAxL3JtNjA5LXNvbGlkaWNvbi13LTAwMi1wLnBuZw-removebg-preview_myrmrf.png',
      'farmName': 'Castro Corn Estate',
      'hectare': 6.0,
    },

    // Fishery Farmers (5)
    {
      'id': '11',
      'farmerName': 'Pedro Bautista',
      'sector': 'Fishery',
      'barangay': 'San Antonio 1',
      'contact': '09345678901',
      'imageUrl':
          'https://res.cloudinary.com/dk41ykxsq/image/upload/v1745590990/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTAxL3JtNjA5LXNvbGlkaWNvbi13LTAwMi1wLnBuZw-removebg-preview_myrmrf.png',
      'farmName': 'Bautista Fishpond',
      'hectare': 2.5,
    },
    {
      'id': '12',
      'farmerName': 'Jose Aquino',
      'sector': 'Fishery',
      'barangay': 'Santa Cruz',
      'contact': '09456789012',
      'imageUrl':
          'https://res.cloudinary.com/dk41ykxsq/image/upload/v1745590990/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTAxL3JtNjA5LXNvbGlkaWNvbi13LTAwMi1wLnBuZw-removebg-preview_myrmrf.png',
      'farmName': 'Aquino Fish Farm',
      'hectare': 3.0,
    },
    {
      'id': '13',
      'farmerName': 'Ramon Delos Reyes',
      'sector': 'Fishery',
      'barangay': 'San Vicente',
      'contact': '09567890123',
      'imageUrl':
          'https://res.cloudinary.com/dk41ykxsq/image/upload/v1745590990/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTAxL3JtNjA5LXNvbGlkaWNvbi13LTAwMi1wLnBuZw-removebg-preview_myrmrf.png',
      'farmName': 'Delos Reyes Tilapia Farm',
      'hectare': 4.2,
    },
    {
      'id': '14',
      'farmerName': 'Luzviminda Navarro',
      'sector': 'Fishery',
      'barangay': 'Concepcion',
      'contact': '09678901234',
      'imageUrl':
          'https://res.cloudinary.com/dk41ykxsq/image/upload/v1745590990/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTAxL3JtNjA5LXNvbGlkaWNvbi13LTAwMi1wLnBuZw-removebg-preview_myrmrf.png',
      'farmName': 'Navarro Fish Hatchery',
      'hectare': 3.5,
    },
    {
      'id': '15',
      'farmerName': 'Armando Rivera',
      'sector': 'Fishery',
      'barangay': 'San Pedro',
      'contact': '09789012345',
      'imageUrl':
          'https://res.cloudinary.com/dk41ykxsq/image/upload/v1745590990/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTAxL3JtNjA5LXNvbGlkaWNvbi13LTAwMi1wLnBuZw-removebg-preview_myrmrf.png',
      'farmName': 'Rivera Aqua Farm',
      'hectare': 5.0,
    },

    // Livestock Farmers (5)
    {
      'id': '16',
      'farmerName': 'Ana Reyes',
      'sector': 'Livestock',
      'barangay': 'San Gregorio',
      'contact': '09456789012',
      'imageUrl':
          'https://res.cloudinary.com/dk41ykxsq/image/upload/v1745590990/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTAxL3JtNjA5LXNvbGlkaWNvbi13LTAwMi1wLnBuZw-removebg-preview_myrmrf.png',
      'farmName': 'Reyes Poultry Farm',
      'hectare': 2.8,
    },
    {
      'id': '17',
      'farmerName': 'Rodolfo Santiago',
      'sector': 'Livestock',
      'barangay': 'Santa Ana',
      'contact': '09567890123',
      'imageUrl':
          'https://res.cloudinary.com/dk41ykxsq/image/upload/v1745590990/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTAxL3JtNjA5LXNvbGlkaWNvbi13LTAwMi1wLnBuZw-removebg-preview_myrmrf.png',
      'farmName': 'Santiago Pig Farm',
      'hectare': 3.5,
    },
    {
      'id': '18',
      'farmerName': 'Teresita Villanueva',
      'sector': 'Livestock',
      'barangay': 'San Lorenzo',
      'contact': '09678901234',
      'imageUrl':
          'https://res.cloudinary.com/dk41ykxsq/image/upload/v1745590990/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTAxL3JtNjA5LXNvbGlkaWNvbi13LTAwMi1wLnBuZw-removebg-preview_myrmrf.png',
      'farmName': 'Villanueva Dairy Farm',
      'hectare': 4.0,
    },
    {
      'id': '19',
      'farmerName': 'Gregorio Lim',
      'sector': 'Livestock',
      'barangay': 'Santa Catalina',
      'contact': '09789012345',
      'imageUrl':
          'https://res.cloudinary.com/dk41ykxsq/image/upload/v1745590990/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTAxL3JtNjA5LXNvbGlkaWNvbi13LTAwMi1wLnBuZw-removebg-preview_myrmrf.png',
      'farmName': 'Lim Cattle Ranch',
      'hectare': 6.2,
    },
    {
      'id': '20',
      'farmerName': 'Maricel Ocampo',
      'sector': 'Livestock',
      'barangay': 'San Francisco',
      'contact': '09890123456',
      'imageUrl':
          'https://res.cloudinary.com/dk41ykxsq/image/upload/v1745590990/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTAxL3JtNjA5LXNvbGlkaWNvbi13LTAwMi1wLnBuZw-removebg-preview_myrmrf.png',
      'farmName': 'Ocampo Goat Farm',
      'hectare': 3.0,
    },

    // Organic Farmers (5)
    {
      'id': '21',
      'farmerName': 'Luis Gonzales',
      'sector': 'Organic',
      'barangay': 'San Isidro',
      'contact': '09567890123',
      'imageUrl':
          'https://res.cloudinary.com/dk41ykxsq/image/upload/v1745590990/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTAxL3JtNjA5LXNvbGlkaWNvbi13LTAwMi1wLnBuZw-removebg-preview_myrmrf.png',
      'farmName': 'Gonzales Organic Farm',
      'hectare': 3.5,
    },
    {
      'id': '22',
      'farmerName': 'Carmen Dela Rosa',
      'sector': 'Organic',
      'barangay': 'Santa Elena',
      'contact': '09678901234',
      'imageUrl':
          'https://res.cloudinary.com/dk41ykxsq/image/upload/v1745590990/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTAxL3JtNjA5LXNvbGlkaWNvbi13LTAwMi1wLnBuZw-removebg-preview_myrmrf.png',
      'farmName': 'Dela Rosa Organic Garden',
      'hectare': 2.0,
    },
    {
      'id': '23',
      'farmerName': 'Rogelio Martinez',
      'sector': 'Organic',
      'barangay': 'San Miguel',
      'contact': '09789012345',
      'imageUrl':
          'https://res.cloudinary.com/dk41ykxsq/image/upload/v1745590990/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTAxL3JtNjA5LXNvbGlkaWNvbi13LTAwMi1wLnBuZw-removebg-preview_myrmrf.png',
      'farmName': 'Martinez Organic Plantation',
      'hectare': 4.8,
    },
    {
      'id': '24',
      'farmerName': 'Corazon Angeles',
      'sector': 'Organic',
      'barangay': 'Santo Niño',
      'contact': '09890123456',
      'imageUrl':
          'https://res.cloudinary.com/dk41ykxsq/image/upload/v1745590990/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTAxL3JtNjA5LXNvbGlkaWNvbi13LTAwMi1wLnBuZw-removebg-preview_myrmrf.png',
      'farmName': 'Angeles Organic Haven',
      'hectare': 3.2,
    },
    {
      'id': '25',
      'farmerName': 'Emilio Tan',
      'sector': 'Organic',
      'barangay': 'Santa Isabel',
      'contact': '09901234567',
      'imageUrl':
          'https://res.cloudinary.com/dk41ykxsq/image/upload/v1745590990/cHJpdmF0ZS9sci9pbWFnZXMvd2Vic2l0ZS8yMDIzLTAxL3JtNjA5LXNvbGlkaWNvbi13LTAwMi1wLnBuZw-removebg-preview_myrmrf.png',
      'farmName': 'Tan Organic Farmstead',
      'hectare': 5.5,
    },
  ];
}
