// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2o4wsvab9MWWkljeOZ3LA4ClrmfhG8kU',
    appId: '1:698351759800:web:50ed1f687e428cad6d9f4d',
    messagingSenderId: '698351759800',
    projectId: 'agritrack-fb6cf',
    authDomain: 'agritrack-fb6cf.firebaseapp.com',
    storageBucket: 'agritrack-fb6cf.firebasestorage.app',
    measurementId: 'G-R8KDP7R7LG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD78ncX_b5UMyLx2bfe6hWw_ttDoEBgquE',
    appId: '1:698351759800:android:2b5edf4b5a3f51016d9f4d',
    messagingSenderId: '698351759800',
    projectId: 'agritrack-fb6cf',
    storageBucket: 'agritrack-fb6cf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZfV2eTOqJfNu2HdiXVQWyU2GrC_iHE2E',
    appId: '1:698351759800:ios:b6b13af97021fe9d6d9f4d',
    messagingSenderId: '698351759800',
    projectId: 'agritrack-fb6cf',
    storageBucket: 'agritrack-fb6cf.firebasestorage.app',
    iosBundleId: 'top.flareline.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZfV2eTOqJfNu2HdiXVQWyU2GrC_iHE2E',
    appId: '1:698351759800:ios:b6b13af97021fe9d6d9f4d',
    messagingSenderId: '698351759800',
    projectId: 'agritrack-fb6cf',
    storageBucket: 'agritrack-fb6cf.firebasestorage.app',
    iosBundleId: 'top.flareline.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2o4wsvab9MWWkljeOZ3LA4ClrmfhG8kU',
    appId: '1:698351759800:web:fcd0d34897919d036d9f4d',
    messagingSenderId: '698351759800',
    projectId: 'agritrack-fb6cf',
    authDomain: 'agritrack-fb6cf.firebaseapp.com',
    storageBucket: 'agritrack-fb6cf.firebasestorage.app',
    measurementId: 'G-NRNNL2T9TX',
  );
}
